### ISSUE TITLE
Rate limited command outputs „1 seconds left“

### ISSUE THREAD

**Issue by MoaufmKlo** [austinhuang0131/disboard-i18n#72]
I‘m not sure if there‘s an easy way to fix this or if I‘m just missing something in the translation.

**Comment by synarvis** [comment]
I think the solution is to use:

`Bitte warte {0, plural, =1{# Sekunde} other{# Sekunden}}`

At least that's the case with the other strings where the same issue would be otherwise.

**Comment by MoaufmKlo** [comment]
Yeah, I'm just confused as the original strong doesn't have this either and therefore didn't include it.

**Comment by MoaufmKlo** [comment]
I'm actually not even sure that would work - only saw it in the php files so far

**Comment by synarvis** [comment]
I'm not sure either, we'd have to wait for Bus or Taki to say something about it.

**Comment by MoaufmKlo** [comment]
@takeaki @austinhuang0131

**Comment by austinhuang0131** [comment]
I don't control if the translation is uploaded or not

**Comment by MoaufmKlo** [comment]
We're asking if we can add the second/seconds string into JavaScript too, or if it only works in php

**Comment by austinhuang0131** [comment]
https://github.com/austinhuang0131/disboard-i18n/blob/master/locales/de.js#L33

**Comment by austinhuang0131** [comment]
sorry hold on

**Comment by austinhuang0131** [comment]
As far as I'm concerned the only way is to make the "second/seconds" another variable and add judgment on the backend which 1. I don't control 2. Too complex for an aesthetic issue. @takeaki still has the final say on this but I personally don't think it's gonna happen.

In short I don't think it's as simple as how it works in php

**Comment by MoaufmKlo** [comment]
Alright.

**Comment by MoaufmKlo** [comment]
I'll close this issue now as it hasn't been discussed on in about tow months. Thanks for your help! 👍
